version: '2'
services:
  web:
    image: opencctv/server:web
    links:
      - mysql:db
    working_dir: /myapp
   # command: bundle install
   # command: rake db:create
   # command: rake db:migrate
   # command: rake db:seed
    #command: mkdir -p /usr/local/opencctv/analytics
    #command: mkdir -p /usr/local/opencctv/vms_connectors
    volumes:
      - /usr/local/opencctv/analytics:/usr/local/opencctv/analytics
      - /usr/local/opencctv/vms_connectors:/usr/local/opencctv/vms_connectors
      - ~/workspace/OpenCCTV/opencctv-web:/myapp
    #  - /Users/Nhutumdai//workspace/OpenCCTV/opencctv-web/app/assets/programs/PluginArchiveValidator:/myapp/app/assets/programs/PluginArchiveValidator
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    container_name: web
    command: /bin/bash
    tty: true
    stdin_open: true
  
  opencctv:
    image: opencctv/server:opencctv
    #links:
    #  - analytic
    #  - mysql:db
    working_dir: /usr/local/opencctv/OpenCCTVServerStarter
    #command: mkdir -p /usr/local/opencctv/analytics
    #command: mkdir -p /usr/local/opencctv/vms_connectors
    volumes:
      - /usr/local/opencctv/analytics:/usr/local/opencctv/analytics
      - /usr/local/opencctv/vms_connectors:/usr/local/opencctv/vms_connectors
      - ~/workspace/OpenCCTV/opencctv-server/opencctv-starter/Release:/usr/local/opencctv/OpenCCTVServerStarter
      - ~/workspace/OpenCCTV/opencctv-server/opencctv-server/Release:/usr/local/opencctv/OpenCCTVServer
      - ~/workspace/OpenCCTV/opencctv-server/opencctv-server/Release:/usr/local/opencctv/Release
      - ~/workspace/OpenCCTV/opencctv-server/opencctv-server/src:/usr/local/opencctv/src
    depends_on:
      - mysql
      - analytic
    container_name: opencctv
    network_mode: "host"
    command: /bin/bash
    tty: true
    stdin_open: true

    
  analytic:
    image: opencctv/server:analytic
    working_dir: /usr/local/opencctv/AnalyticStarter
    #command: mkdir -p /usr/local/opencctv/analytics
    #command: mkdir -p /usr/local/opencctv/vms_connectors
    ports:
      - "5555:5555"
    volumes:
      - /usr/local/opencctv/analytics:/usr/local/opencctv/analytics
      - /usr/local/opencctv/vms_connectors:/usr/local/opencctv/vms_connectors
      - ~/workspace/OpenCCTV/analytic-server/analytic-starter/Release:/usr/local/opencctv/AnalyticStarter
      - ~/workspace/OpenCCTV/analytic-server/analytic-server/Release:/usr/local/opencctv/AnalyticRunner
      #- /home/nhamphu/Workspaces/OpenCCTV/opencctv-dependencies/dependencies:/root/dependencies
    container_name: analytic
    network_mode: "host"
    command: /bin/bash
    tty: true 
    stdin_open: true

  mysql:
    image: opencctv:mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
  #  command: sh -c 'service mysql restart'
  #  command: sh -c 'exec mysql -hlocalhost -uroot -p1234  < /tmp/opencctv_results_db.sql'
  #  volumes:
  #    - /home/nhamphu/Workspaces/docker-compose/opecctv/opencctv_results_db.sql:/tmp/opencctv_results_db.sql
    container_name: mysql
